version: '3.1'

services:
  stats-db-postgres:
    image: postgres:13.7-alpine
    container_name: stats-db-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: stats-service/server/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db-postgres
    environment:
      - DB_HOST=stats-db-postgres
      - DB_PORT=5432
      - DB_NAME=stats-db-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STATS_SERVER_PORT=9090

  main-service:
    build: main-service/main-server/
    container_name: main-server
    ports:
      - "8080:8080"
      - "8091:8091"
    depends_on:
      - main-db-postgres
      - stats-server
    environment:
      - MAIN_SERVER_PORT=8080
      - STAT_SERVER_URL=http://stats-server:9090
      - APP_NAME=main-service
      - DB_HOST=main-db-postgres
      - DB_PORT=5432
      - DB_NAME=main-db-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-db-postgres:
    image: postgres:13.7-alpine
    container_name: main-db-postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=main-db-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    hostname: main-db-postgres